name: Build and Test

on:
  push:
    branches: [ "master" , "release/*"]
  pull_request:
    branches: [ "master", "release/*" ]

jobs:
  build:
    runs-on:  ubuntu-latest

    steps:
    - name: Checkout codebase
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Run tests
      run: |
        poetry shell
        pytest


